# Browsersync config
BROWSERSYNC:
  # URL of local development server goes here (ex. http://localsite.dev)
  url: "https://uni.test"
  key: "/Users/jontryggviunnarsson/.localhost-ssl/localhost.key"
  crt: "/Users/jontryggviunnarsson/.localhost-ssl/localhost.crt"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "> 5%"
  - 'Firefox ESR'

# Set to true if you want static asset revisioning, helpful for cache busting
REVISIONING: false  

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "library/dist"
  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "library/src/**/*"
    - "!library/src/{images,images/**/*,js,js/**/*,scss,scss/**/*}"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/owl.carousel/src/scss/"
    - "node_modules/slick-slider/slick/"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "library/src/js/avista-app.js"
    - "library/src/js/page-frontpage.js"
    - "library/src/js/single-product.js"
    - "library/src/js/page-offerings.js"
    - "library/src/js/page-news.js"
    - "library/src/js/elements/element-mailchimp.js"
    - "library/src/js/elements/element-quote.js"
    # Paths to sass entry points for building different css files for different page loads
  entries_sass:
    - "library/src/scss/avista-app.scss"
    - "library/src/scss/avista-woocommerce.scss"
  # Paths for the package task to include/exclude in .zip archive
  package:
    - "**/*"
    - "!**/node_modules/**"
    - "!**/packaged/**"
    - "!**/src/**"
    - "!**/codesniffer.ruleset.xml"
    - "!**/composer.json"
    - "!**/composer.lock"
    - "!**/config.yml"
    - "!**/config.default.yml"
    - "!**/gulpfile.babel.js"
    - "!**/package.json"
    - "!**/package-lock.json"
    - "!**/webpack.config.js"
  # Paths for PHP CodeSniffer
  phpcs:
    - "**/*.php"
    - "!wpcs"
    - "!wpcs/**"  
