name: Flywheel SSH Deploy
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Remove node mdules
      uses: JesseTG/rm@v1.0.3
      with:
        path: node_modules/
    - name: Remove package
      uses: JesseTG/rm@v1.0.3
      with:
        path: package-lock.json
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: ${{ secrets.SSH_USER }}
        ARGS: -rltgoDzvO --exclude .git --exclude .github
        TARGET: /www/wp-content/themes/uni-hub