name: Flywheel SSH Deploy
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - uses: actions/checkout@v2
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: ${{ secrets.SSH_USER }}
        ARGS: -rltgoDzvO --exclude .git --exclude .github
        TARGET: /www/wp-content/themes/uni-hub