name: Flywheel SSH Deployer
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
       node-version: 'lts/*'
       cache: 'yarn'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run build task
      run: yarn build
    - name: Deploy to Server 🗂️
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: "uni-is.tempurl.host"
        REMOTE_USER: ${{ secrets.SSH_USER }}
        ARGS: "-rlgoDzvc -i"
        EXCLUDE: "/node_modules/, /.github/, /.git/, /package-lock.json"
        TARGET: "./site/public_html/wp-content/themes/uni-hub/"

